name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          make all
      - uses: actions/upload-artifact@master
        with:
          name: cheatsheets
          path: target
